### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by oredaze** [aeosynth/bk#31]
Terminal: foot
OS: Gentoo
on Wayland
```
thread 'main' panicked at /home/rat/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bk-0.6.0/src/epub.rs:60:63:
called `Result::unwrap()` on an `Err` value: UnknownEntityReference("nbsp", TextPos { row: 12, col: 32 })
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
   3: bk::epub::Epub::new
   4: bk::main
```

**Comment by aeosynth** [comment]
That's an old bug, https://github.com/aeosynth/bk/issues/13 . Your book has bad xml, can't do anything unless we change the xml library.
